name: food_hub
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.13.0
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_facebook_auth: ^6.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.3
  flutter_riverpod: ^2.4.3
  flutter_screenutil: ^5.9.0
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  flutter_localizations: 
    sdk: flutter
  path_provider: ^2.1.1
  dio: ^5.3.3
  pinput: ^3.0.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.3
  flutter_zoom_drawer: ^3.1.1
  flutter_flavorizr: ^2.2.1
  cached_network_image: ^3.3.0
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  get_it: ^7.6.4
  firebase_remote_config: ^4.3.5
  firebase_analytics: ^10.7.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  style:
    path: style

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: '#FE724C'
  image: assets/images/splash.png
  android_12:
    color: '#FE724C'
    image: assets/images/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: SofiaPro
  #     fonts:
  #       - asset: assets/fonts/SofiaProRegular.otf
  #       - asset: assets/fonts/SofiaProBold.otf
  #         weight: 700
  #       - asset: assets/fonts/SofiaProExtraLight.otf
  #         weight: 200
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/CustomIcons.ttf
flutter_intl:
  enabled: true