// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJj196_-aWabKOb9jMQAFT5GkIfXI7EU',
    appId: '1:387912745201:android:4c851891c2f60b73f2e950',
    messagingSenderId: '387912745201',
    projectId: 'foodhub-f4c39',
    storageBucket: 'foodhub-f4c39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0AoM9BAxdd4iCzOubvuaGUK12C5thu3g',
    appId: '1:387912745201:ios:0a424532b541e489f2e950',
    messagingSenderId: '387912745201',
    projectId: 'foodhub-f4c39',
    storageBucket: 'foodhub-f4c39.appspot.com',
    androidClientId: '387912745201-31ngpfqqkkro6apk7uo48vshiijvg853.apps.googleusercontent.com',
    iosClientId: '387912745201-6lu5uq88v49dc491skofq71fogj0478p.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodHub',
  );
}
